### ISSUE TITLE
Use Case: See Animations

### ISSUE THREAD

**Issue by TheAspiredOne** [401AR/W17401AR#74]
<a href="https://github.com/mcmorris"><img src="https://avatars.githubusercontent.com/u/6345864?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcmorris](https://github.com/mcmorris)**
_Thursday Feb 02, 2017 at 03:15 GMT_
_Originally opened as https://github.com/Hegberg/401AR/issues/40_

----

UC: See Animations

**Comment by mcmorris** [comment]
Priority shifted to "Nice to have."

**Comment by ljuarezr** [comment]
Feature to be implemented in future iterations.
