### ISSUE TITLE
Use Case: Pause Simulation

### ISSUE THREAD

**Issue by TheAspiredOne** [401AR/W17401AR#75]
<a href="https://github.com/mcmorris"><img src="https://avatars.githubusercontent.com/u/6345864?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcmorris](https://github.com/mcmorris)**
_Thursday Feb 02, 2017 at 03:16 GMT_
_Originally opened as https://github.com/Hegberg/401AR/issues/41_

----

Pause Simulation

**Comment by mcmorris** [comment]
Issue being treated as OUT OF SCOPE.
