### ISSUE TITLE
Use Case: Reset Findings

### ISSUE THREAD

**Issue by TheAspiredOne** [401AR/W17401AR#76]
<a href="https://github.com/mcmorris"><img src="https://avatars.githubusercontent.com/u/6345864?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcmorris](https://github.com/mcmorris)**
_Thursday Feb 02, 2017 at 03:17 GMT_
_Originally opened as https://github.com/Hegberg/401AR/issues/42_

----

UC: Reset Findings

**Comment by mcmorris** [comment]
Done.
