### ISSUE TITLE
Final Manual Testing

### ISSUE THREAD

**Issue by TheAspiredOne** [401AR/W17401AR#82]
<a href="https://github.com/mcmorris"><img src="https://avatars.githubusercontent.com/u/6345864?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcmorris](https://github.com/mcmorris)**
_Thursday Feb 02, 2017 at 03:22 GMT_
_Originally opened as https://github.com/Hegberg/401AR/issues/48_

----

Final Manual Testing

**Comment by mcmorris** [comment]
Manual testing is testing that is not done directly with the client.  This is for us testing the full-scope of our deliverables are properly tested and bug free.  Given that I've found at least five errors after this was closed, our testing is not finished.

**Comment by mcmorris** [comment]
Code submission deadline has now passed, manual testing therefore concludes.
